version: '3.8'

services:   
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  redis:
    image: redis:latest

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'a_random_secret_key'
      AIRFLOW__WEBSERVER__WORKERS: 1
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'

      # ✅ SMTP Configuration Starts
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
      AIRFLOW__SMTP__SMTP_SSL: 'False'
      AIRFLOW__SMTP__SMTP_USER: kishoretheshuttler@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: ngba bklw xujo dhnc
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: justgamingusage@gmail.com
      # ✅ SMTP Configuration Ends

    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'a_random_secret_key'
      AIRFLOW__CORE__FERNET_KEY: ''

      # ✅ SMTP Configuration Starts
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
      AIRFLOW__SMTP__SMTP_SSL: 'False'
      AIRFLOW__SMTP__SMTP_USER: kishoretheshuttler@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: ngba bklw xujo dhnc
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: kishoretheshuttler@gmail.com
      # ✅ SMTP Configuration Ends

    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    restart: always

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
      - redis
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Kishore --lastname G --role Admin --email admin@example.com"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'a_random_secret_key'
      AIRFLOW__CORE__FERNET_KEY: ''
    volumes:
      - ./dags:/opt/airflow/dags

volumes:
  postgres-db-volume:
